[package]
name = "kyrie-config"

version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
